baseURL = 'https://dku-plant-futures.github.io/'
theme = 'PaperMod'
title = 'DKU Plant Futures'

enableEmoji = true

defaultContentLanguage = 'en'

disqusShortname = 'dku-plant-futures'

timeZone = 'Asia/Shanghai'

[taxonomies]
tag = 'tags'

[menu]

[[menu.main]]
identifier = "research"
name = "Guide"
url = "/guide"
weight = 5

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags"
weight = 15

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search"
weight = 20

[[menu.main]]
identifier = "forum"
name = "Forum"
url = "https://github.com/dku-plant-futures/dku-plant-futures.github.io/discussions"
weight = 25

[[menu.main]]
identifier = "chat"
name = "Chat"
url = "https://teams.microsoft.com/l/team/19%3As6SZBTPi7s1f4rHlBfk9aozuwQEAwzQO-yboEB1bxwM1%40thread.tacv2/conversations?groupId=855d3ffe-800c-46a5-a8b4-ec2e656d031f&tenantId=cb72c54e-4a31-4d9e-b14a-1ea36dfac94c"
weight = 30

[params]
author = 'Plant Futures DKU'
description = "This is the website for Plant Futures DKU Club."
social = true
ShowShareButtons = true
ShareButtons = ["reddit", "facebook", "whatsapp", "telegram"]
displayFullLangName = true
comments = true
ShowReadingTime = true
ShowPostNavLinks = true

[params.homeInfoParams]
Title = 'Blog Posts'
Content = 'What we have done and will do ---'

[[params.profileMode.buttons]]
name = "Blog"
url = "/blog"

[[params.socialIcons]]
name = "email"
url = "mailto:4c1abb1e.ProdDuke.onmicrosoft.com@amer.teams.ms"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/plantfuturesdku/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/dku-plant-futures/dku-plant-futures.github.io/discussions"

[[params.socialIcons]]
name = "rss"

[[params.socialIcons]]
name = "other"
url = "https://teams.microsoft.com/l/team/19%3As6SZBTPi7s1f4rHlBfk9aozuwQEAwzQO-yboEB1bxwM1%40thread.tacv2/conversations?groupId=855d3ffe-800c-46a5-a8b4-ec2e656d031f&tenantId=cb72c54e-4a31-4d9e-b14a-1ea36dfac94c"

[params.editPost]
URL = "https://github.com/dku-plant-futures/dku-plant-futures.github.io/tree/hugo/content"
Text = "Suggest Edits"
appendFilePath = true

[outputs]
home = ["HTML", "RSS", "JSON"] # necessary for search
