baseURL = 'https://dku-plant-futures.github.io/'
theme = 'PaperMod'
title = 'DKU Plant Futures'

enableEmoji = true

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

disqusShortname = 'dku-plant-futures'

timeZone = 'Asia/Shanghai'

[languages.en]

[languages.en.menu]

[[languages.en.menu.main]]
identifier = "guide"
name = "Guide"
url = "/guide"
weight = 5

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 10

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags"
weight = 15

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search"
weight = 20

[[languages.en.menu.main]]
identifier = "forum"
name = "Forum"
url = "https://github.com/dku-plant-futures/dku-plant-futures.github.io/discussions"
weight = 25

[[languages.en.menu.main]]
identifier = "chat"
name = "Chat"
url = "https://teams.microsoft.com/l/team/19%3As6SZBTPi7s1f4rHlBfk9aozuwQEAwzQO-yboEB1bxwM1%40thread.tacv2/conversations?groupId=855d3ffe-800c-46a5-a8b4-ec2e656d031f&tenantId=cb72c54e-4a31-4d9e-b14a-1ea36dfac94c"
weight = 30

[languages]

[languages.zh]
title = '昆杜植物未来社'
weight = 1

[languages.zh.menu]

[[languages.zh.menu.main]]
identifier = "guide"
name = "指南"
url = "/guide"
weight = 5

[[languages.zh.menu.main]]
identifier = "about"
name = "关于"
url = "/about"
weight = 10

[[languages.zh.menu.main]]
identifier = "tags"
name = "标签"
url = "/tags"
weight = 15

[[languages.zh.menu.main]]
identifier = "search"
name = "搜索"
url = "/search"
weight = 20
[[languages.zh.menu.main]]
identifier = "forum"
name = "论坛"
url = "https://github.com/dku-plant-futures/dku-plant-futures.github.io/discussions"
weight = 25

[[languages.zh.menu.main]]
identifier = "chat"
name = "群聊"
url = "https://teams.microsoft.com/l/team/19%3As6SZBTPi7s1f4rHlBfk9aozuwQEAwzQO-yboEB1bxwM1%40thread.tacv2/conversations?groupId=855d3ffe-800c-46a5-a8b4-ec2e656d031f&tenantId=cb72c54e-4a31-4d9e-b14a-1ea36dfac94c"
weight = 30

[languages.zh.params]
author = '昆杜植物未来社'
description = "昆山杜克大学植物未来社"

[languages.zh.params.homeInfoParams]
Title = '博客文章'
Content = '我们的努力和计划 ---'

[params]
author = 'Plant Futures DKU'
description = "This is the website for Plant Futures DKU Club."
social = true
ShowShareButtons = true
ShareButtons = ["reddit", "facebook", "whatsapp", "telegram"]
displayFullLangName = true
comments = false
ShowReadingTime = true
ShowPostNavLinks = true

[params.homeInfoParams]
Title = 'Blog Posts'
Content = 'What we have done and will do ---'

[[params.profileMode.buttons]]
name = "Blog"
url = "/blog"

[[params.socialIcons]]
name = "email"
url = "mailto:4c1abb1e.ProdDuke.onmicrosoft.com@amer.teams.ms"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/plantfuturesdku/"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/plant-future-dku-95782333a/"

[[params.socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/plantfuturesdku.bsky.social"

[[params.socialIcons]]
name = "mastodon"
url = "https://mastodon.world/@plantfuturesdku"

[[params.socialIcons]]
name = "reddit"
url = "https://www.reddit.com/user/PlantFutureDKU/"

[[params.socialIcons]]
name = "rss"

[params.editPost]
URL = "https://github.com/dku-plant-futures/dku-plant-futures.github.io/tree/hugo/content"
Text = "Suggest Edits"
appendFilePath = true

[outputs]
home = ["HTML", "RSS", "JSON"] # necessary for search

[taxonomies]
tag = 'tags'
